### ISSUE TITLE
Making table head floating to the top

### ISSUE THREAD

**Issue by kunalpat25** [iamrohitsuthar/gocoronago#11]
It would be easier for the visitor to be able to read what's the heading of values in table are. 
When one scrolls down, he has to go up again to see the heading of that column. Overall UI is great, only this is the problem.

I would like to work on this feature- floating table head.

**Comment by iamrohitsuthar** [comment]
okay.

**Comment by iamrohitsuthar** [comment]
There is one problem.
**BUG:**
When you load the website on a desktop mode, the table head is stick at the top for only half of the table. 

The issue disappears when you switch to a mobile view and then after scrolling the table when you switch back to desktop mode.

**How to reproduce**
1. Load the website in desktop mode.
2. Scroll the table

Please fix the problem and send PR!

**Comment by kunalpat25** [comment]
Actually the problem is not consistent. When you restore the window and again maximize it,this issue doesn't appear. Rather it doesn't affect much .
