### ISSUE TITLE
Make new-feature branch Responsive

### ISSUE THREAD

**Issue by saglaniharsh** [iamrohitsuthar/gocoronago#6]
Both Related Info and Helpline aren't responsive at all

Helpline:
![image](https://user-images.githubusercontent.com/19408070/77251514-bb252000-6c74-11ea-95e4-980f65b5bd3f.png)

Related info:
![image](https://user-images.githubusercontent.com/19408070/77251546-ead42800-6c74-11ea-8b4e-61275274c1c7.png)

**Comment by iamrohitsuthar** [comment]
Please review the changes and let me know.

**Comment by saglaniharsh** [comment]
> 
> 
> Please review the changes and let me know.

Will do.

**Comment by saglaniharsh** [comment]
Seems fine
